#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'

cookbook 'git', '= 4.1.0'

cookbook 'curl'

cookbook 'vim'

cookbook 'apache2'

cookbook 'mysql'

cookbook 'php'

cookbook 'composer'

cookbook 'phing'

cookbook 'hipsnip-jetty'

cookbook 'hipsnip-solr'

cookbook 'memcached'

cookbook 'varnish', '= 1.0.2'

cookbook 'php-fpm'

cookbook 'nodejs'

cookbook 'grunt_cookbook',
         :git => 'git://github.com/MattSurabian/grunt_cookbook.git'

cookbook 'ruby-ng'

cookbook 'selenium'

cookbook 'openssl'
